# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/telemetry/telemetry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/telemetry/telemetry.proto',
  package='telemetry',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1fproto/telemetry/telemetry.proto\x12\ttelemetry\"\xb4\x02\n\ttelemetry\x12\x12\n\ntime_alive\x18\x01 \x02(\x03\x12\x13\n\x0b\x64\x65scription\x18\x02 \x02(\t\x12\x31\n\npublishers\x18\x03 \x02(\x0b\x32\x1d.telemetry.telemetry.endpoint\x12\x32\n\x0bsubscribers\x18\x04 \x02(\x0b\x32\x1d.telemetry.telemetry.endpoint\x12.\n\x07\x63lients\x18\x05 \x02(\x0b\x32\x1d.telemetry.telemetry.endpoint\x12.\n\x07servers\x18\x06 \x02(\x0b\x32\x1d.telemetry.telemetry.endpoint\x1a\x37\n\x08\x65ndpoint\x12\x15\n\rnum_endpoints\x18\x01 \x02(\x05\x12\x14\n\x0cnum_messages\x18\x02 \x02(\x05')
)




_TELEMETRY_ENDPOINT = _descriptor.Descriptor(
  name='endpoint',
  full_name='telemetry.telemetry.endpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_endpoints', full_name='telemetry.telemetry.endpoint.num_endpoints', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_messages', full_name='telemetry.telemetry.endpoint.num_messages', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=355,
)

_TELEMETRY = _descriptor.Descriptor(
  name='telemetry',
  full_name='telemetry.telemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_alive', full_name='telemetry.telemetry.time_alive', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='telemetry.telemetry.description', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publishers', full_name='telemetry.telemetry.publishers', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subscribers', full_name='telemetry.telemetry.subscribers', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clients', full_name='telemetry.telemetry.clients', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='servers', full_name='telemetry.telemetry.servers', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TELEMETRY_ENDPOINT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=355,
)

_TELEMETRY_ENDPOINT.containing_type = _TELEMETRY
_TELEMETRY.fields_by_name['publishers'].message_type = _TELEMETRY_ENDPOINT
_TELEMETRY.fields_by_name['subscribers'].message_type = _TELEMETRY_ENDPOINT
_TELEMETRY.fields_by_name['clients'].message_type = _TELEMETRY_ENDPOINT
_TELEMETRY.fields_by_name['servers'].message_type = _TELEMETRY_ENDPOINT
DESCRIPTOR.message_types_by_name['telemetry'] = _TELEMETRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

telemetry = _reflection.GeneratedProtocolMessageType('telemetry', (_message.Message,), {

  'endpoint' : _reflection.GeneratedProtocolMessageType('endpoint', (_message.Message,), {
    'DESCRIPTOR' : _TELEMETRY_ENDPOINT,
    '__module__' : 'proto.telemetry.telemetry_pb2'
    # @@protoc_insertion_point(class_scope:telemetry.telemetry.endpoint)
    })
  ,
  'DESCRIPTOR' : _TELEMETRY,
  '__module__' : 'proto.telemetry.telemetry_pb2'
  # @@protoc_insertion_point(class_scope:telemetry.telemetry)
  })
_sym_db.RegisterMessage(telemetry)
_sym_db.RegisterMessage(telemetry.endpoint)


# @@protoc_insertion_point(module_scope)
