#!/bin/bash


python_stuff () {
  if ! type virtualenv &> /dev/null; then
    sudo apt install virtualenv
  fi
  virtualenv -p python3 .venv
  source ./.venv/bin/activate
}

pip_stuff () {
  pip3 install conan
}


python_stuff
pip_stuff
