# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/common/cmd_vel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/common/cmd_vel.proto',
  package='movement',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1aproto/common/cmd_vel.proto\x12\x08movement\"6\n\x0b\x64rive_train\x12\x12\n\nlinear_vel\x18\x01 \x02(\x05\x12\x13\n\x0b\x61ngular_vel\x18\x02 \x02(\x05\"\x1d\n\x06\x63\x61mera\x12\x13\n\x0b\x61ngular_vel\x18\x01 \x02(\x05\"*\n\x03gun\x12\x10\n\x08left_mag\x18\x01 \x02(\x05\x12\x11\n\tright_mag\x18\x02 \x02(\x05')
)




_DRIVE_TRAIN = _descriptor.Descriptor(
  name='drive_train',
  full_name='movement.drive_train',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear_vel', full_name='movement.drive_train.linear_vel', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angular_vel', full_name='movement.drive_train.angular_vel', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=94,
)


_CAMERA = _descriptor.Descriptor(
  name='camera',
  full_name='movement.camera',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='angular_vel', full_name='movement.camera.angular_vel', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=125,
)


_GUN = _descriptor.Descriptor(
  name='gun',
  full_name='movement.gun',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='left_mag', full_name='movement.gun.left_mag', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right_mag', full_name='movement.gun.right_mag', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['drive_train'] = _DRIVE_TRAIN
DESCRIPTOR.message_types_by_name['camera'] = _CAMERA
DESCRIPTOR.message_types_by_name['gun'] = _GUN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

drive_train = _reflection.GeneratedProtocolMessageType('drive_train', (_message.Message,), {
  'DESCRIPTOR' : _DRIVE_TRAIN,
  '__module__' : 'proto.common.cmd_vel_pb2'
  # @@protoc_insertion_point(class_scope:movement.drive_train)
  })
_sym_db.RegisterMessage(drive_train)

camera = _reflection.GeneratedProtocolMessageType('camera', (_message.Message,), {
  'DESCRIPTOR' : _CAMERA,
  '__module__' : 'proto.common.cmd_vel_pb2'
  # @@protoc_insertion_point(class_scope:movement.camera)
  })
_sym_db.RegisterMessage(camera)

gun = _reflection.GeneratedProtocolMessageType('gun', (_message.Message,), {
  'DESCRIPTOR' : _GUN,
  '__module__' : 'proto.common.cmd_vel_pb2'
  # @@protoc_insertion_point(class_scope:movement.gun)
  })
_sym_db.RegisterMessage(gun)


# @@protoc_insertion_point(module_scope)
